apiVersion: v1
kind: Service
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    app: hello
    tier: web
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: "127.0.0.1"
